# pull official base image
FROM postgres:12.0-alpine

# set environment variables
# ENV POSTGRES_DB=tictactoedb
# ENV POSTGRES_USER=tictactoeuser
# ENV POSTGRES_PASSWORD=tictactoepassword

EXPOSE 5432