version: "3.9"
services:
  backend:
    container_name: tictactoe_backend
    env_file: .env
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: tictactoe_db
    build:
      context: ./database
    env_file: .env    
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
    