apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - image: student246700/tictactoe_backend
          name: tictactoe-backend
          ports:
            - containerPort: 8000
          resources: {}
      restartPolicy: Always
status: {}
