apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "3000"
      port: 3000
      nodePort: 30001
    
  selector:
    io.kompose.service: frontend
status:
  loadBalancer: {}
