# -*- mode: ruby -*-
require 'yaml'

current_dir = File.dirname(File.expand_path(__FILE__))
app_config = YAML.load_file("#{current_dir}/config.yaml")

Vagrant.configure("2") do |config|

  config.vm.define "db" do |db|
    db.vm.box = "debian/bullseye64"
    db.vm.provision "shell", path: "./db_config.sh"
    db.vm.network "private_network", ip: app_config["db_ip"]
  end

  config.vm.define "web" do |web|
    web.vm.box = "debian/bullseye64"
    web.vm.synced_folder "./", "/mnt"
    web.vm.network "private_network", ip: app_config["web_ip"]
    web.vm.network "forwarded_port", guest: 5000, host: 8080

    web.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "web.yml"
      ansible.become = true
    end

  end

end